import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      import Script from 'next/script'

export const metadata = {
  title: 'Check Ton Véhicule – Assistant IA pour voitures d’occasion',
  description:
    'Analyse IA d’annonces auto, détection de risques, aide à la négociation. Gagnez 500–2000€ sur votre prochaine voiture.',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        {children}

        {/* Plausible custom script */}
        <Script
          async
          src="https://plausible.io/js/pa-wrlyMwgrkJe5XcixXf6Nm.js"
        />

        <Script id="plausible-init">
          {`
            window.plausible = window.plausible || function() {
              (plausible.q = plausible.q || []).push(arguments)
            };
            plausible.init = plausible.init || function(i) {
              plausible.o = i || {};
            };
            plausible.init();
          `}
        </Script>
      </body>
    </html>
  )
}
      </body>
    </html>
  );
}
